import Article from '@/components/feed/article'

function TestArticle(){
	return(
		<Article html='<h2 id="what-is-happening-with-ukraine-s-incursion-into-russia-and-how-far-has-it-got-">What is happening with Ukraine’s incursion into Russia and how far has it got?</h2>
<p>Ukraine launched a surprise incursion with armour and infantry into the Kursk and Belgorod regions of Russia on 6 August, involving thousands of troops amounting to 14 brigades. While initial details of the attack were murky, both Kyiv and Moscow have now acknowledged the operation into the Russian border regions, while independent analysts have verified claims about the scale of the advance by geolocating images posted by Ukrainian troops.</p>
<p>In his recent first public comments on the operation, Ukraine’s top military commander, Gen Oleksandr Syrskyi, claimed on Monday that Ukraine now controlled about 1,000 sq km (386 sq miles) of the region. The claim was largely confirmed on the Russian side. Alexei Smirnov, the acting governor of the Kursk region, told the Russian president, Vladimir Putin, via a videoconference briefing on Monday that Ukrainian forces controlled 28 Russian settlements, including towns and villages up to 18 miles (30 km) inside Russia.</p>
<p>Footage from just outside the village of Glushkovo in Kursk showed damage to a bridge crossing the Seym River. Video from Kursk’s Belovsky district showed damage to cars and roads. Despite claims by Russian military bloggers on Sunday that the situation had stabilised, new incursions into western Kursk were reported north-west of the Ukrainian city of Sumy. </p>
<p>According to the Institute for the Study of War, geolocated footage showed that Ukrainian forces had recently been conducting operations in Sudzha and northern Zaoleshenka. Some Russian bloggers claimed that Ukraine had seized Sudzha. Footage posted on social media appeared to show ambushes on rival columns around Sudzha, including on Ukrainian forces in the village of Giri.</p>
<p>Smirnov said 121,000 people had been evacuated from their homes in the Kursk region, while 11,000 had been evacuated from Belgorod region.</p>
<h3 id="what-sort-of-resistance-has-ukraine-faced-">What sort of resistance has Ukraine faced?</h3>
<p>While Ukraine has previously launched numerous small incursions and sabotage raids into Russian border regions, the scale of this incursion caught Moscow off guard and it initially struggled to respond to the attack. Since the weekend, Moscow has announced a sweeping counter-terror operation in Kursk and two other border regions. The Russian defence ministry said on Sunday that its forces were fighting Ukrainian troops in the areas of the settlements of Tolpino, Zhuravli, and Obshchy Kolodez.</p>
<p>Maria Zakharova, a foreign ministry spokesperson, said a tough response from Russia’s armed forces “will not take long”. The Russian defence ministry stated that its forces had blocked an attempt by Ukrainian mobile groups to forge deep into Russian territory near Kauchuk. The Russian ally Belarus has also said it was increasing its own troop numbers at its border after claiming Ukraine had entered its airspace with drones. Pasi Paroinen, an analyst with the Finland-based Black Bird Group open-source intelligence agency, which monitors the war, noted that the toughest phase of Ukraine’s incursion was likely to begin now as Russian reserves entered the fray.</p>
<h3 id="why-is-ukraine-doing-it-">Why is Ukraine doing it?</h3>
<p>While the Ukrainian operation is under tight secrecy, and its goals remain unclear, the advance brings Kyiv’s forces closer to key supply lines inside Russia supporting Russia’s ongoing offensive in eastern Ukraine. Sudzha in Kursk is also the site of the only pumping station for Russian natural gas to reach Europe through Ukraine.</p>
<p>Ukraine’s president, Volodymyr Zelenskiy, stated that the incursion was designed “to put pressure on the aggressor Russia” and push “the war into the aggressor’s territory”. Zelenskiy emphasized that thousands of strikes on Ukraine’s territory launched from Russia’s Kursk region deserved a fair response. </p>
<p>Speaking on Monday at a meeting with top security and defence officials, Putin indicated that the attack appeared to reflect Kyiv’s attempt to achieve a better negotiating position in possible future talks to end the war. He added that Ukraine might have hoped the attack would cause public unrest in Russia, but it had failed to do so. Putin claimed that the number of volunteers to join the Russian military had increased because of the incident, reinforcing the idea that the enemy will continue trying to destabilise the situation in the border zone.</p>
<p>Russia’s main task, he stated, was to “drive the enemy out of our territories and, together with the border service, to ensure reliable cover of the state border”.</p>'/>
	)
}

export default TestArticle
